# Generated by Django 6.1.1 on 2026-09-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
